### PR TITLE
Grocery list

### LINKED ISSUE #5: A user should be able to enter the ingredients for each recipe in a running grocery list. List will render in separate browserWindow.

### PR DESCRIPTION
**Pull request by gprocell927**
Closes #5 
A user is able to open Savery in the menu bar and click on the grocery list button. A grocery list opens in a new browserWindow and the menubar app remains open. The user is able to enter an item and quantity and save it. The item and quantity will display below the form in a list and will save to the JSON object.
**With pictures: **

**My emotions: **

### CODE REVIEW

**Review by stephanieea — APPROVED** [review]
1[](https://media.giphy.com/media/rhaIsgMSRHaUg/giphy.gif)

**Comment by gprocell927** [comment]
I committed a change. Per Regis' caveat about adjusting NPM modules. The grocery list still opens, but the main app will also open in a new browserWindow.

**Review by apsitos — APPROVED** [review]

**Pull request merged**
